(package "lol"
         "0.1.1"
         "Emacs lisp implementation of games from book 'Land of Lisp'")

(files "*.el"
       ("lisp" "lisp/*.el"))

(source gnu)
(source melpa)

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
